export const products = [
  {
    id: 1,
    sponsored: true,
    title: "Google Pixel 9A (Porcelain, 256 GB)",
    image:
      "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/0/q/f/-original-imahadxg8mgjzrfh.jpeg?q=70",
    rating: 4.5,
    reviews: "8,289",
    reviewCount: "548",
    features: [
      "8 GB RAM | 256 GB ROM",
      "15.96 cm (6.28 inch) Full HD+ Display",
      "48MP + 12MP | 12MP Front Camera",
      "5100 mAh Battery",
      "Tensor G4 Processor",
      "1 Year Domestic Warranty",
    ],
    price: "39,999",
    oldPrice: "49,999",
    discount: 20,
    exchange: "Upto ₹32,900 Off on Exchange",
    bankOffer: "Bank Offer",
    assured: true,
  },
  {
    id: 2,
    sponsored: true,
    title: "Iphone (Porcelain, 256 GB)",
    image:
      "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/x/w/8/-original-imahh652uegnztz3.jpeg?q=70",
    rating: 4.5,
    reviews: "8,289",
    reviewCount: "548",
    features: [
      "8 GB RAM | 256 GB ROM",
      "15.96 cm (6.28 inch) Full HD+ Display",
      "48MP + 12MP | 12MP Front Camera",
      "5100 mAh Battery",
      "Tensor G4 Processor",
      "1 Year Domestic Warranty",
    ],
    price: "39,999",
    oldPrice: "49,999",
    discount: 20,
    exchange: "Upto ₹32,900 Off on Exchange",
    bankOffer: "Bank Offer",
    assured: true,
  },
  {
    id: 3,
    sponsored: true,
    title: "Galaxy S26 Ultra",
    image:
      "https://images.samsung.com/in/smartphones/galaxy-s26-ultra/buy/kv_exclusive_animated_PC_noText.mp4",
    rating: 4.5,
    reviews: "8,289",
    reviewCount: "548",
    features: [
      "8 GB RAM | 256 GB ROM",
      "15.96 cm (6.28 inch) Full HD+ Display",
      "48MP + 12MP | 12MP Front Camera",
      "5100 mAh Battery",
      "Tensor G4 Processor",
      "1 Year Domestic Warranty",
    ],
    price: "1,49,999",
    oldPrice: "1,89,999",
    discount: 20,
    exchange: "Upto ₹32,900 Off on Exchange",
    bankOffer: "Bank Offer",
    assured: true,
  },
];
